### ISSUE TITLE
Error on Downloading CSV Result from SPARQL Query Execution

### ISSUE THREAD

**Issue by jpdom** [OP-TED/ted-sparql-editor#5]
### Observed Behaviour
Executing a sample query and choosing the CSV result format presents the results correctly on the results page but returns an error when clicking on the "Download" button present on the results page.

### Query (just changed the date from the [sample](https://docs.ted.europa.eu/ODS/latest/samples/query-1.html#_query))
```sparql 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?publicationNumber ?procedureType ?noticeType ?formType
WHERE {
  FILTER (?publicationDate = "2024-12-02"^^xsd:date)
  GRAPH ?g {
    ?notice a epo:Notice ;
            epo:hasPublicationDate ?publicationDate ;
            epo:hasNoticePublicationNumber ?publicationNumber ;
            epo:hasNoticeType ?noticeTypeUri ;
            epo:hasFormType ?formTypeUri ;
            epo:refersToProcedure [
                 a epo:Procedure ;
                 epo:hasProcedureType ?procedureTypeUri
           ] .
  }

  \# Retrieve the label in english for noticeTypeUri
  ?noticeTypeUri a skos:Concept ;
                 skos:prefLabel ?noticeType .
  FILTER (lang(?noticeType) = "en")

  \# Retrieve the label in english for formTypeUri
  ?formTypeUri a skos:Concept ;
               skos:prefLabel ?formType .
  FILTER (lang(?formType) = "en")

  \# Retrieve the label in english for procedureTypeUri
  ?procedureTypeUri a skos:Concept ;
                    skos:prefLabel ?procedureType .
  FILTER (lang(?procedureType) = "en")
}
```

### Error page 
https://publications.europa.eu/webapi/rdf/sparql?default-graph-uri=&query=PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20PREFIX%20epo%3A%20%3Chttp%3A%2F%2Fdata.europa.eu%2Fa4g%2Fontology%23%3E%20PREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%20SELECT%20%3FpublicationNumber%20%3FprocedureType%20%3FnoticeType%20%3FformType%20WHERE%7BFILTER(%3FpublicationDate%20%3D%20%222024-12-02%22%5E%5Exsd%3Adate)GRAPH%20%3Fg%7B%3Fnotice%20a%20epo%3ANotice%3Bepo%3AhasPublicationDate%20%3FpublicationDate%3Bepo%3AhasNoticePublicationNumber%20%3FpublicationNumber%3Bepo%3AhasNoticeType%20%3FnoticeTypeUri%3Bepo%3AhasFormType%20%3FformTypeUri%3Bepo%3ArefersToProcedure%20%5B%20a%20epo%3AProcedure%3Bepo%3AhasProcedureType%20%3FprocedureTypeUri%20%5D.%7D%23%20Retrieve%20the%20label%20in%20english%20for%20noticeTypeUri%20%3FnoticeTypeUri%20a%20skos%3AConcept%3Bskos%3AprefLabel%20%3FnoticeType.FILTER(lang(%3FnoticeType)%3D%20%22en%22)%23%20Retrieve%20the%20label%20in%20english%20for%20formTypeUri%20%3FformTypeUri%20a%20skos%3AConcept%3Bskos%3AprefLabel%20%3FformType.FILTER(lang(%3FformType)%3D%20%22en%22)%23%20Retrieve%20the%20label%20in%20english%20for%20procedureTypeUri%20%3FprocedureTypeUri%20a%20skos%3AConcept%3Bskos%3AprefLabel%20%3FprocedureType.FILTER(lang(%3FprocedureType)%3D%20%22en%22)%7D&format=text%2Fcsv&timeout=30000
```
Virtuoso 37000 Error SP030: SPARQL compiler, line 4: syntax error

SPARQL query:

#output-format:text/csv
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX epo: <http://data.europa.eu/a4g/ontology#> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT ?publicationNumber ?procedureType ?noticeType ?formType WHERE{FILTER(?publicationDate = "2024-12-02"^^xsd:date)GRAPH ?g{?notice a epo:Notice;epo:hasPublicationDate ?publicationDate;epo:hasNoticePublicationNumber ?publicationNumber;epo:hasNoticeType ?noticeTypeUri;epo:hasFormType ?formTypeUri;epo:refersToProcedure [ a epo:Procedure;epo:hasProcedureType ?procedureTypeUri ].}# Retrieve the label in english for noticeTypeUri ?noticeTypeUri a skos:Concept;skos:prefLabel ?noticeType.FILTER(lang(?noticeType)= "en")# Retrieve the label in english for formTypeUri ?formTypeUri a skos:Concept;skos:prefLabel ?formType.FILTER(lang(?formType)= "en")# Retrieve the label in english for procedureTypeUri ?procedureTypeUri a skos:Concept;skos:prefLabel ?procedureType.FILTER(lang(?procedureType)= "en")}
```

**Comment by victoriobentivogli** [comment]
Hello João,

Thank you for bringing this issue to our attention.

We identified two important points:

- Your SPARQL query contains comment lines that start with "\\#" instead of "#".
- There was an unexpected behavior in our application when downloading results from queries that included comments.

We have now resolved the download issue, and the application should function correctly. We appreciate your help in identifying and reporting this.

Kind regards
